/* Generated By:JavaCC: Do not edit this line. MyEventParserConstants.java */
package edu.curtin.terminalgriddemo.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyEventParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 2;
  /** RegularExpression Id. */
  int DATE = 3;
  /** RegularExpression Id. */
  int TIME = 4;
  /** RegularExpression Id. */
  int DURATION = 5;
  /** RegularExpression Id. */
  int TITLE = 6;
  /** RegularExpression Id. */
  int EVENT = 7;
  /** RegularExpression Id. */
  int ALL_DAY_EVENT = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int PLUGIN_CONTENT = 11;
  /** RegularExpression Id. */
  int MULTILINE_PYTHON = 12;
  /** RegularExpression Id. */
  int MULTILINE_STRING = 13;
  /** RegularExpression Id. */
  int PLUGIN = 14;
  /** RegularExpression Id. */
  int SCRIPT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<WHITESPACE>",
    "<DATE>",
    "<TIME>",
    "<DURATION>",
    "<TITLE>",
    "<EVENT>",
    "<ALL_DAY_EVENT>",
    "<ID>",
    "<STRING>",
    "<PLUGIN_CONTENT>",
    "<MULTILINE_PYTHON>",
    "<MULTILINE_STRING>",
    "<PLUGIN>",
    "<SCRIPT>",
  };

}
